apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # => carlos@google.com
  DB_USER_EMAIL: Y2FybG9zQGdvb2dsZS5jb20=

  # => EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=